### ISSUE TITLE
False positive on github.event.pull_request.base.sha?

### ISSUE THREAD

**Issue by christophetd** [TinderSec/gh-workflow-auditor#4]
github.event.pull_request.base.sha sounds like it triggers a hit but cannot be controlled arbitrarily

**Comment by christophetd** [comment]
same for `github.event.pull_request.number`

**Comment by christophetd** [comment]
Read too fast the blog post.

**Comment by christophetd** [comment]
No, actually it seems it holds. I think such a configuration is _not_ vulnerable as it checks out the base branch (not the PR code):

```
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
```
